site_name: mkdocs-template
copyright: 'Author: <a href="mailto:844804539@qq.com">844804539@qq.com</a>'

theme:
    name: bootstrap
extra_css:
    - style.css
extra_javascript:
    - injection.js
nav:
    - 首页: index.md
    - Menu:
        - SubMenu1: README.md
        - SubMenu2: README.md
        - SubMenu3: README.md